### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by ghost** [atom-community/lint#1]
**error report from atom:**

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.4
### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At C:\Users\Eu\AppData\Local\atom\app-1.7.3\resources\app.asar\src\display-buffer.js:1056

Error: Cannot decorate a destroyed marker
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (C:\Users\Eu\AppData\Local\atom\app-1.7.3\resources\app.asar\src\display-buffer.js:1056:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (C:\Users\Eu\AppData\Local\atom\app-1.7.3\resources\app.asar\src\text-editor.js:1346:33)
    at LinterViews.renderBubble [as _renderBubble] (C:/Users/Eu/.atom/packages/linter/lib/linter-views.js:86:43)
    at file:///C:/Users/Eu/.atom/packages/linter/lib/helpers.coffee:23:18
```
### Commands

```
  2x -2:45.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:45 core:paste (atom-text-editor.editor.is-focused)
     -2:36.8.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -2:32.1.0 core:delete (atom-text-editor.editor.is-focused)
  3x -2:25.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:22.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:59 core:save (atom-text-editor.editor.is-focused)
  2x -0:53.8.0 editor:newline (atom-text-editor.editor.is-focused)
  7x -0:46.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:34.5.0 core:cut (atom-text-editor.editor.is-focused)
     -0:30.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:30.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:28.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:23.7.0 core:copy (atom-text-editor.editor.is-focused)
     -0:21.4.0 core:paste (atom-text-editor.editor.is-focused)
     -0:17.4.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-sass, v0.1.0
file-icons, v1.7.11
highlight-selected, v0.11.2
linter, v1.11.4
linter-sass-lint, v1.4.3
minimap, v4.23.5
minimap-highlight-selected, v4.4.0
pigments, v0.26.3
Sass-Syntax-Highlight, v0.1.1

# Dev
No dev packages
```

What was doing?
- coding SCSS and linting

The atom windows was split vertically to the right
![untitled](https://cloud.githubusercontent.com/assets/3471090/15272022/e8ee81bc-1a33-11e6-877c-38a5c38a63db.png)

I was editing at the right side (has warnings).
started editing another file at left side that has warnings too.
the linter automatically opened at the left panel the file that is at the right. When I closed this file the linter crashed.

**Comment by joefitzgerald** [comment]
Wrong package. You're looking for the steelbrain linter.
